[package]
name = "loukanikos"
version = "0.1.0"
edition = "2021"

[dependencies]
etherparse = "0.19.0"
json = "0.12.4"
macaddr = "1.0.1"
pcap = "2.2.0"
regex = "1.11.1"
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.140"
toml = "0.8.20"
u4 = "0.1.2"
