[[cad_rms_software]]
Exhibitor = "365Labs"
Summary = "365Labs helps agencies tackle the challenges of the next 20 years. 365 is a one cloud platform supported by modern, purpose-built Apps that replace a dozen or more existing systems, significantly impr..."
Booth = "4101"

[[cad_rms_software]]
Exhibitor = "Abel Police"
Summary = "null"
Booth = "387"

[[cad_rms_software]]
Exhibitor = "CentralSquare Technologies"
Summary = "CentralSquare is an industry leader in public safety and public administration software, serving over 8,000 organizations from the largest metropolitan city to counties and towns of every size across ..."
Booth = "773"

[[cad_rms_software]]
Exhibitor = "CODY Systems"
Summary = "CODY Systems is a PA-based, woman-owned company that provides data-driven solutions to law enforcement and government agencies of all sizes and tiers. Solutions include the scalable, multi-tenant, ful..."
Booth = "3409"

[[cad_rms_software]]
Exhibitor = "Computer Information Systems, Inc."
Summary = "Since 1985, CIS has had a single business: Public Safety Computer Systems. All of our personnel, equipment, resources and energy are devoted to bringing the most advanced, reliable and best maintaine..."
Booth = "702"

[[cad_rms_software]]
Exhibitor = "Critical Response Group. Inc."
Summary = "Critical Response Group comprises a team of US Special Operation veterans, public safety professionals, technical experts, and business executives that use our collective experiences to improve the na..."
Booth = "975"

[[cad_rms_software]]
Exhibitor = "Hexagon and Leica Geosystems"
Summary = "Hexagon improves public safety and security through reliable data, systems and capabilities by helping police manage and share information, enhance crime and accident investigations, ensure officer sa..."
Booth = "553"

[[cad_rms_software]]
Exhibitor = "i3 Verticals"
Summary = "i3 Verticals offering simplifies and streamlines workflows across all government departments. With decades of industry experience and deep domain expertise, i3 Verticals Public Sector connects entire ..."
Booth = "693"

[[cad_rms_software]]
Exhibitor = "Karda Inc."
Summary = "null"
Booth = "2242"

[[cad_rms_software]]
Exhibitor = "Kaseware, Inc."
Summary = "Kaseware helps organizations solve complex investigations quickly and efficiently, ensuring the safety of people and the protection of property. Our software allows you to collect, analyze, and connec..."
Booth = "573"

[[cad_rms_software]]
Exhibitor = "LexisNexis Coplogic Solutions"
Summary = "While crash fatalities have reached crisis levels within the U.S., agencies are looking for traffic safety experts to help them get ahead of the problem. LexisNexis Coplogic Solutions is introducing ..."
Booth = "1315, 1322"

[[cad_rms_software]]
Exhibitor = "Motorola Solutions"
Summary = "Motorola Solutions provides mission-critical intelligence that gives law enforcement the power to access information, stream video and collaborate in real-time. By integrating voice communications, s..."
Booth = "741"

[[cad_rms_software]]
Exhibitor = "National Public Safety Group"
Summary = "null"
Booth = "797"

[[cad_rms_software]]
Exhibitor = "New in Blue"
Summary = "null"
Booth = "4310"

[[cad_rms_software]]
Exhibitor = "Niche Technology Inc."
Summary = "At Niche, we focus on the information demands of frontline officers when seconds count. The responsive NicheRMS365 UI provides a consistent, intuitive user experience on phone, tablet, laptop and desk..."
Booth = "1413"

[[cad_rms_software]]
Exhibitor = "Omnigo Software"
Summary = "Omnigo Software, a leading provider of public safety, incident reporting, and security management software solutions, has long been the preferred choice for law enforcement, education, healthcare, gam..."
Booth = "211"

[[cad_rms_software]]
Exhibitor = "Oracle America, Inc."
Summary = "Oracle is on a mission, through technology, to make work life simpler, safer, and more productive for our policing and law enforcement first responders. We are developing technologies to make this pos..."
Booth = "1023"

[[cad_rms_software]]
Exhibitor = "ProPhoenix Corporation"
Summary = "Public Safety Software: Law & Fire CAD, Law & Fire Mobile, Law & Fire iOS & Android apps, Law RMS, Fire RMS, Corrections Management System, Internal Affairs software, Pawn Registry and trackin..."
Booth = "4109"

[[cad_rms_software]]
Exhibitor = "PSTrax"
Summary = "PSTrax is software solution for Checklists and Inventory Management that helps Police Departments automate critical operations checks for Vehicles, Stations, Equipment, Supplies and Controlled Substan..."
Booth = "2107"

[[cad_rms_software]]
Exhibitor = "Samsung"
Summary = "Samsung provides innovative mobile solutions extending public safety communications beyond the vehicle. We partner with agencies to deliver force-multiplying technology that deliver the information fi..."
Booth = "1563"

[[cad_rms_software]]
Exhibitor = "Tait Communications"
Summary = "null"
Booth = "3330"

[[cad_rms_software]]
Exhibitor = "TBL Systems, Inc."
Summary = "TBL Systems, Inc. is the leading provider in Secure-Cloud Records Management/RMS, Mobile-Dispatch, Electronic Citation, Digital Evidence Management and Traffic Reporting. RMS by TBL Systems is affo..."
Booth = "3523"

[[cad_rms_software]]
Exhibitor = "Tyler Technologies"
Summary = "With 30 years of public sector experience, Tyler Technologies knows what first responders need. Streamlining processes, collecting data, and improving communications are only a few of the many benefit..."
Booth = "823"

[[cad_rms_software]]
Exhibitor = "Vehicle Management Solutions"
Summary = "Vehicle Management Solutions (VMS) is the nation’s largest provider of dispatch, vehicle storage, and traffic incident management. VMS combines high quality local services, a cutting-edge technology p..."
Booth = "4219"

[[cad_rms_software]]
Exhibitor = "Versaterm"
Summary = "Versaterm is a global public safety solutions company helping agencies transform their organizations by providing innovative solutions, expertise, and an unwavering dedication to customer service. For..."
Booth = "1373"

[[cad_rms_software]]
Exhibitor = "Zetron, Inc."
Summary = "Zetron is a leading provider of communications technology and services that help save lives and enable critical operations. Zetron solutions are highly interoperable, configurable, and scalable, offer..."
Booth = "435"
