[["communication equipment"]]
Exhibitor = "3Si"
Summary = "At 3Si, we deliver comprehensive security solutions that leverage real-time data to protect assets and people across various industries. Our innovative approach integrates advanced video management sy..."
Booth = "423"

[["communication equipment"]]
Exhibitor = "AED | Patrol PC"
Summary = "Patrol PC® RhinoTab® UltraRugged® touch screen MDTs are optimized for use by First Responders. Designed and manufactured in the USA, our industrial grade tablets are purpose-built and designed for ope..."
Booth = "3807"

[["communication equipment"]]
Exhibitor = "BIXOLON America, Inc."
Summary = "None"
Booth = "3530"

[["communication equipment"]]
Exhibitor = "BK Technologies"
Summary = "BK Technologies® is a U.S. Manufacturer of APCO P25 Radio Communications equipment for State, Local, and Federal Government Agencies. BK manufactures high specification communications equipment of uns..."
Booth = "2909"

[["communication equipment"]]
Exhibitor = "Bunker Supply"
Summary = "Bunker Supply is a design-forward US military contractor that develops and manufactures optimized equipment for agents in the field. We are uniquely equipped to support the mission of our Government a..."
Booth = "2274"

[["communication equipment"]]
Exhibitor = "Ceragon Networks Inc"
Summary = "None"
Booth = "688"

[["communication equipment"]]
Exhibitor = "Daktronics"
Summary = "Advance your control with high performance LED Video Wall Technology from the most secure provider in the industry, Daktronics, based in South Dakota, USA. Our products are manufactured with vigilant ..."
Booth = "1002"

[["communication equipment"]]
Exhibitor = "DragonForce"
Summary = "DragonForce is an industry leading provider of command and control, incident management solutions to the domestic and international public safety community. Its DragonForce team collaboration platform..."
Booth = "1488"

[["communication equipment"]]
Exhibitor = "Ear Phone Connection, Inc."
Summary = "Since 1997, The Earphone Connection, Inc. has worked diligently to deliver professional and innovative two-way radio accessories to the law enforcement industry. Headquartered in Southern California, ..."
Booth = "601"

[["communication equipment"]]
Exhibitor = "Eventide Communications"
Summary = "Eventide’s NexLog DX-Series IP-based communications recording systems have been specifically designed for mission critical 24/7 operation in emergency call-taking, dispatch, air traffic management and..."
Booth = "302"

[["communication equipment"]]
Exhibitor = "Exacom"
Summary = "None"
Booth = "1689"

[["communication equipment"]]
Exhibitor = "First Arriving"
Summary = "Accelerate your department’s communication with First Arriving’s digital dashboards and PORTAL intranet. Our dashboards streamline your communication efforts and create efficiencies across your tea..."
Booth = "605"

[["communication equipment"]]
Exhibitor = "Frontline Communications"
Summary = "Frontline Communications, a division of Pierce Manufacturing, is a leading manufacturer of highly customized turnkey command, communications, and emergency response vehicles. Since 1983 we have built ..."
Booth = "1773"

[["communication equipment"]]
Exhibitor = "GoodSAM"
Summary = "GoodSAM provides cutting edge 911 video and geolocating systems that are radically changing policing. Our systems are unique with many advanced features including: - Open any 911 callers cameras with..."
Booth = "4307"

[["communication equipment"]]
Exhibitor = "goTenna"
Summary = "None"
Booth = "2606"

[["communication equipment"]]
Exhibitor = "JVCKENWOOD"
Summary = "JVCKENWOOD is a global manufacturer leading the way on P25 communications and Professional Systems Solutions. As a pioneer in the technology with decades of technical expertise developing mission-cri..."
Booth = "301"

[["communication equipment"]]
Exhibitor = "L3Harris"
Summary = "None"
Booth = "1485"

[["communication equipment"]]
Exhibitor = "LDV, Inc."
Summary = "LDV is the leading manufacturer of special service vehicles, including Mobile Command Centers, SWAT/Rapid Response Vehicles, Bomb/EOD Trucks, Mobile Laboratories/DUI Response Vehicles, Equipment Vehic..."
Booth = "633"

[["communication equipment"]]
Exhibitor = "Leonardo/ELSAG"
Summary = "At Leonardo, we are dedicated to providing proprietary advanced ALPR technology to law enforcement agencies, parking authorities, toll operators and access control organizations through our ELSAG ALPR..."
Booth = "1303"

[["communication equipment"]]
Exhibitor = "LiveU"
Summary = "LiveU is a leading developer of live video broadcasting and streaming solutions for unmanned aerial and ground vehicles (UAV / Drone, UGV). With over 5,000 customers in 150 countries, our technology i..."
Booth = "1979"

[["communication equipment"]]
Exhibitor = "LRAD by Genasys"
Summary = "LRAD® is Law Enforcement's Communication System of Choice. LRAD systems broadcast audible voice messages and attention-commanding alert tones with exceptional vocal clarity from close range to 2,000 m..."
Booth = "341"

[["communication equipment"]]
Exhibitor = "Mobile Pro Systems"
Summary = "We design and manufacture creative mobile surveillance systems for real-time monitoring in nearly any environment. Every product has been developed with ease of use, practicality, and the highest qual..."
Booth = "1951"

[["communication equipment"]]
Exhibitor = "Motorola Solutions"
Summary = "Motorola Solutions provides mission-critical intelligence that gives law enforcement the power to access information, stream video and collaborate in real-time. By integrating voice communications, s..."
Booth = "741"

[["communication equipment"]]
Exhibitor = "Mutualink, Inc."
Summary = "Mutualink, Inc. is the leading technology provider of a best-in-class intelligent multimedia network that enables public safety community partners to securely share voice, text, video, and data for in..."
Booth = "1757"

[["communication equipment"]]
Exhibitor = "N-ear Inc"
Summary = "N•ear is a Florida based American company that was originally founded in Copenhagen Denmark in 2018. The company manufactures and sells premium audio equipment. Our premier engineers, audiological res..."
Booth = "1985"

[["communication equipment"]]
Exhibitor = "NOBLE SUPPLY & LOGISTICS"
Summary = "None"
Booth = "429"

[["communication equipment"]]
Exhibitor = "OTTO Engineering"
Summary = "OTTO Engineering designs and manufactures innovative two-way radio accessories, hearing protection and location tracking equipment developed for high-precision applications in mission critical environ..."
Booth = "2610"

[["communication equipment"]]
Exhibitor = "Pelsue"
Summary = "None"
Booth = "202"

[["communication equipment"]]
Exhibitor = "Peplink"
Summary = "Peplink provides a complete SD-WAN environment including edge routers, antennas, and access points which leverage SpeedFusion Technology to connect and even aggregate multiple fixed or cellular WAN li..."
Booth = "2612"

[["communication equipment"]]
Exhibitor = "Pocketalk"
Summary = "None"
Booth = "3633"

[["communication equipment"]]
Exhibitor = "Regroup Mass Notification"
Summary = "Since 2006, Regroup Mass Notification has provided a cloud-based, multi-channel mass notification platform for emergency and routine applications. Serving the educational community, enterprise, financ..."
Booth = "512"

[["communication equipment"]]
Exhibitor = "Samsung"
Summary = "Samsung provides innovative mobile solutions extending public safety communications beyond the vehicle. We partner with agencies to deliver force-multiplying technology that deliver the information fi..."
Booth = "1563"

[["communication equipment"]]
Exhibitor = "SILYNX Communications, Inc"
Summary = "None"
Booth = "241"

[["communication equipment"]]
Exhibitor = "SoundGear"
Summary = "None"
Booth = "378"

[["communication equipment"]]
Exhibitor = "Sunny Communications"
Summary = "Sunny Communications specializes in used/refurbished radios and infrastructure equipment. Based out of Colorado, we have 20,000+ sqft of warehouse space dedicated to sales, repair, rental and trade-in..."
Booth = "1063"

[["communication equipment"]]
Exhibitor = "Tait Communications"
Summary = "None"
Booth = "3330"

[["communication equipment"]]
Exhibitor = "Telex Radio Dispatch"
Summary = "Telex Radio Dispatch is the leading manufacturer of IP control for two-way radio communications. Capable of deployment in both distributed and server-based architectures, our solutions offer the ultim..."
Booth = "323"

[["communication equipment"]]
Exhibitor = "Vasco Electronics LLC"
Summary = "None"
Booth = "2916"

[["communication equipment"]]
Exhibitor = "Ver-Mac, Inc."
Summary = "Ver-Mac is a leading manufacturer of mobile electronic traffic control equipment and lighting/security equipment. With a strong presence in both the Canadian and US markets, Ver-Mac products are distr..."
Booth = "3108"

[["communication equipment"]]
Exhibitor = "Verizon Frontline"
Summary = "Verizon serves as a trusted partner to the public sector, from rural communities to the largest State and Federal agencies. We enable better government through our best-in-class networks, innovative s..."
Booth = "1001"

[["communication equipment"]]
Exhibitor = "Wanco Inc."
Summary = "Wanco Public Safety Solutions for law enforcement help make your community safer. Deploy our systems anywhere for reliable, unmanned, 24/7 operation for high-incident areas, transportation routes, con..."
Booth = "1817"

[["communication equipment"]]
Exhibitor = "XSponse"
Summary = "None"
Booth = "2305"

[["communication equipment"]]
Exhibitor = "Zebra Technologies"
Summary = "Zebra Technologies helps public safety agencies monitor, anticipate, and accelerate workflows by empowering first responders and ensuring that inventory, property, evidence, and assets are securely vi..."
Booth = "1355"

[["communication equipment"]]
Exhibitor = "Zetron, Inc."
Summary = "Zetron is a leading provider of communications technology and services that help save lives and enable critical operations. Zetron solutions are highly interoperable, configurable, and scalable, offer..."
Booth = "435"
