[[forensics]]
Exhibitor = "908 Devices"
Summary = "908 Devices Inc. is revolutionizing chemical analysis with its simple handheld and desktop devices, addressing life-altering applications. The Company’s devices are used at the point-of-need to interr..."
Booth = "1575"
Prefixes = []

[[forensics]]
Exhibitor = "Ace Computers"
Summary = "Ace Computers is a 40-Year old SI providing the FINEST Deskside/Portable_Forensic Workstations. We also provide full field kits,datacenters and are THE leader in password cracking appliances. We hold ..."
Booth = "991"
Prefixes = ["5C:5A:4C:7"]

[[forensics]]
Exhibitor = "Alcohol Countermeasure Systems"
Summary = "Alcohol Countermeasure Systems (ACS) is an international group of companies with over 40 years of experience developing innovative technology to prevent impaired driving. A leading designer and manufa..."
Booth = "3004"
Prefixes = ["70:B3:D5:FD:0"]

[[forensics]]
Exhibitor = "Amped Software USA Inc."
Summary = "Amped Software sets the standard for image and video forensics. Our software solutions are used by the top law enforcement, military, and government agencies worldwide. The company focuses on develop..."
Booth = "913"
Prefixes = []

[[forensics]]
Exhibitor = "Animal Legal Defense Fund - Criminal Justice Progr"
Summary = "Our Criminal Justice Program attorneys & experts provide free legal assistance and training for law enforcement professionals handling animal abuse investigations nationwide. Our expertise covers al..."
Booth = "1191"
Prefixes = []

[[forensics]]
Exhibitor = "Barrier By Design ~ Scene Shields"
Summary = "Barrier by Design's Scene Shields privacy and security barriers secure accident & emergency sites in less than 5 minutes, without using tools. Protect first responders, victims, evidence, patrons a..."
Booth = "2258"
Prefixes = []

[[forensics]]
Exhibitor = "Berla Corporation"
Summary = "Berla Corporation creates solutions for investigators to identify, acquire, and analyze critical information stored within vehicle systems. The average vehicle generates over a terabyte of data eac..."
Booth = "2301"
Prefixes = []

[[forensics]]
Exhibitor = "CAT Labs"
Summary = "CAT Labs is a Woman-Owned Small Business (WOSB) and a recipient of a SBIR phase 1 award that develops technology to equip law enforcement, defense, and intelligence agencies with tools and training to..."
Booth = "4211"
Prefixes = []

[[forensics]]
Exhibitor = "Collision & Crime Forensic Solutions"
Summary = "None"
Booth = "2616"
Prefixes = []

[[forensics]]
Exhibitor = "DATAPILOT"
Summary = "DATAPILOT specializes in the area of mobile forensics and digital intelligence, we deliver real-time value with proven technological innovations. DATAPILOT came about after identifying a need ..."
Booth = "2246"
Prefixes = []

[[forensics]]
Exhibitor = "Evidence Grade"
Summary = "We are your sole source provider of Evidence Grade: CD-R - 700MB DVD-R - 4.7GB DVD+R-Dual Layer - 8.5GB BD-R - 25GB BD-R Dual Layer - 50GB BD-R-XL - 100GB. Also available: Custom USB Cards..."
Booth = "3000"
Prefixes = []

[[forensics]]
Exhibitor = "EvidenceIQ"
Summary = "Rapid crime gun intelligence to help your team close more cases, faster. Ballistics IQ is the first and only automated triage solution on the market, providing instant crime gun intel. Immediate..."
Booth = "2701"
Prefixes = []

[[forensics]]
Exhibitor = "Exterro"
Summary = "None"
Booth = "2279"
Prefixes = []

[[forensics]]
Exhibitor = "FARO Technologies Inc."
Summary = "FARO® enables public safety, law enforcement and fire professionals to capture, analyze and visualize data to provide unbiased 2D and 3D digital information for investigation and pre-incident planning..."
Booth = "1241"
Prefixes = [
    "BC:34:00:B",
    "70:B3:D5:93:6"
]

[[forensics]]
Exhibitor = "Focal Forensics Redaction"
Summary = "Focal Forensics is an award-winning media forensic service trusted by private organizations, lawyers, school districts, and law enforcement personnel. Focal Forensics specializes in Audio, Video, and ..."
Booth = "1813"
Prefixes = []

[[forensics]]
Exhibitor = "LabVantage Solutions INC"
Summary = "LabVantage Solutions, founded in 1983, is a recognized leader in laboratory software solutions with more than 1500 installations worldwide. Serving numerous industries, including Forensics, the compan..."
Booth = "394"
Prefixes = []

[[forensics]]
Exhibitor = "Lifeloc Technologies"
Summary = "For over 30 years, Lifeloc Technologies has been a global leader in Law Enforcement breath alcohol testing technology. From its U.S. headquarters, Lifeloc designs, engineers and manufactures precision..."
Booth = "3635"
Prefixes = []

[[forensics]]
Exhibitor = "Magnet Forensics"
Summary = "None"
Booth = "697"
Prefixes = []

[[forensics]]
Exhibitor = "Mission Darkness"
Summary = "None"
Booth = "315"
Prefixes = []

[[forensics]]
Exhibitor = "Mystaire"
Summary = "Chain of custody and evidence processing is at the core of Mystaire’s forensic containment equipment. Mystaire’s products are engineered and designed to provide superior safety to both the law enforce..."
Booth = "1958"
Prefixes = []

[[forensics]]
Exhibitor = "Oak Analytics"
Summary = "Narc Ranger™ is a groundbreaking solution that revolutionizes narcotic detection at exceptional value. Its cost-effectiveness, accuracy, non-destructive, in-package detection capability and on-site ra..."
Booth = "2244"
Prefixes = []

[[forensics]]
Exhibitor = "Othram, Inc"
Summary = "None"
Booth = "2309"
Prefixes = []

[[forensics]]
Exhibitor = "OUR Rescue"
Summary = "Help rescue those in need from sex trafficking and child exploitation until every person is safe. In the United States and Canada, OUR Rescue develops relationships with law enforcement agencies and o..."
Booth = "3528"
Prefixes = []

[[forensics]]
Exhibitor = "Parsons"
Summary = "Parsons (NYSE:PSN) is a leading disruptive technology provider in the national security and global infrastructure markets, with capabilities across cyber and intelligence, space and missile defense, t..."
Booth = "3723"
Prefixes = []

[[forensics]]
Exhibitor = "Penlink"
Summary = "For 35 years, PenLink has been the industry-preferred provider for communications, surveillance, and forensics data analysis. Our state-of-the-art solutions help law enforcement collect, normalize, an..."
Booth = "3001"
Prefixes = []

[[forensics]]
Exhibitor = "Pro-gard Products"
Summary = "For over 55 years, Pro-gard Products has been serving the law enforcement community. We provide the safest, most durable law enforcement products designed to perform on the open road. Taking pride in ..."
Booth = "471"
Prefixes = []

[[forensics]]
Exhibitor = "Projectina AG"
Summary = "Founded in 1946 PROJECTINA AG is a Swiss Company specializing in the field of development and manufacture of optical precision instruments and OEM modules for demanding technical areas in niche market..."
Booth = "2277"
Prefixes = []

[[forensics]]
Exhibitor = "Sirchie"
Summary = "Sirchie manufactures high-quality criminal investigation, tactical, surveillance, and other police-related solutions including customized special purpose vehicles. We deliver industry-leading trainin..."
Booth = "2223"
Prefixes = []

[[forensics]]
Exhibitor = "TRM Labs, Inc."
Summary = "TRM Labs is a blockchain intelligence company that helps financial institutions, crypto businesses, and government agencies detect and investigate crypto-related financial crime and fraud. Every day, ..."
Booth = "240"
Prefixes = []

[[forensics]]
Exhibitor = "TSN US LLC"
Summary = "None"
Booth = "2278"
Prefixes = []
