[["investigation surveillance detection"]]
Exhibitor = "3Si"
Summary = "At 3Si, we deliver comprehensive security solutions that leverage real-time data to protect assets and people across various industries. Our innovative approach integrates advanced video management sy..."
Booth = "423"

[["investigation surveillance detection"]]
Exhibitor = "908 Devices"
Summary = "908 Devices Inc. is revolutionizing chemical analysis with its simple handheld and desktop devices, addressing life-altering applications. The Company’s devices are used at the point-of-need to interr..."
Booth = "1575"

[["investigation surveillance detection"]]
Exhibitor = "Austin Microwave, Inc."
Summary = "None"
Booth = "795"

[["investigation surveillance detection"]]
Exhibitor = "Axis Communications"
Summary = "Axis enables a smarter and safer world by creating solutions for improving security and business performance. As a network technology company and industry leader, Axis offers solutions in video survei..."
Booth = "1749"

[["investigation surveillance detection"]]
Exhibitor = "CARFAX"
Summary = "CARFAX for Police provides trusted insights and solutions that power law enforcement agencies to create better protected communities, and safer, more efficient agencies. More than 5,800 data-sharing l..."
Booth = "1923"

[["investigation surveillance detection"]]
Exhibitor = "CAT Labs"
Summary = "CAT Labs is a Woman-Owned Small Business (WOSB) and a recipient of a SBIR phase 1 award that develops technology to equip law enforcement, defense, and intelligence agencies with tools and training to..."
Booth = "4211"

[["investigation surveillance detection"]]
Exhibitor = "Cellebrite"
Summary = "Cellebrite delivers industry-leading technology and services that are trusted by law enforcement and enterprises worldwide, to help protect communities, secure their most valuable assets, and bring ju..."
Booth = "1547"

[["investigation surveillance detection"]]
Exhibitor = "Chorus Intelligence Inc"
Summary = "Chorus Intelligence is an award-winning international software company, providing law enforcement agencies with cutting-edge data search, cleansing and analysis tools. The Chorus Intelligence Suite (C..."
Booth = "1455"

[["investigation surveillance detection"]]
Exhibitor = "Clearview AI"
Summary = "Clearview AI is a revolutionary, all-in-one, facial recognition platform designed to support federal, state, and local law enforcement in their shared mission to help keep communities safe. Agencies c..."
Booth = "1658"

[["investigation surveillance detection"]]
Exhibitor = "Constant Technologies"
Summary = "Constant Technologies specializes in creating public safety command centers tailored to the unique needs and requirements of each agency - offering turnkey solutions that include mission critical vide..."
Booth = "1535"

[["investigation surveillance detection"]]
Exhibitor = "Crime Gun Intelligence Technologies (CGIT)"
Summary = "Crime Gun Intelligence Technologies (CGIT) provides law enforcement with the FireFLY LE gunshot detection/geolocation system. The FireFLY LE system is a trusted and reliable technology that is used t..."
Booth = "2103"

[["investigation surveillance detection"]]
Exhibitor = "CRIMEWATCH Technologies, Inc"
Summary = "CRIMEWATCH is a platform built for Law Enforcement to drive transparency through the sharing of information and policy to local communities. A packaged solution to leverage your operational activity t..."
Booth = "3502"

[["investigation surveillance detection"]]
Exhibitor = "Critical Tech Solutions"
Summary = "The Rapid All-Terrain Tower (RATT) is a portable mast that gives you the ability to deploy a variety of devices in minutes including surveillance cameras, radio antennas, signal boosters, outdoor WiFi..."
Booth = "1595"

[["investigation surveillance detection"]]
Exhibitor = "Databuoy Corporation"
Summary = "Databuoy manufactures the Shotpoint® gunfire detection and localization system. Shotpoint® senses gunfire, isolates the source, and instantly transmits shooter location alerts. Through the proprietary..."
Booth = "2011"

[["investigation surveillance detection"]]
Exhibitor = "DragonForce"
Summary = "DragonForce is an industry leading provider of command and control, incident management solutions to the domestic and international public safety community. Its DragonForce team collaboration platform..."
Booth = "1488"

[["investigation surveillance detection"]]
Exhibitor = "Echodyne"
Summary = "Echodyne is a U.S. designer and manufacturer of advanced radar solutions for critical infrastructure protection applications. The company’s proprietary metamaterials electronically scanned array (MESA..."
Booth = "1973"

[["investigation surveillance detection"]]
Exhibitor = "Ekin Smart City Solutions"
Summary = "None"
Booth = "2197"

[["investigation surveillance detection"]]
Exhibitor = "Ensurity"
Summary = "None"
Booth = "3824"

[["investigation surveillance detection"]]
Exhibitor = "Equature"
Summary = "Equature stands as a venerable pillar in the realm of public safety software, with a rich history spanning over 50 years. Established in the United States, we've been at the forefront of pioneering so..."
Booth = "2707"

[["investigation surveillance detection"]]
Exhibitor = "EvidenceIQ"
Summary = "Rapid crime gun intelligence to help your team close more cases, faster. Ballistics IQ is the first and only automated triage solution on the market, providing instant crime gun intel. Immediate..."
Booth = "2701"

[["investigation surveillance detection"]]
Exhibitor = "Evolv Technology"
Summary = "Evolv Technology (NASDAQ: EVLV) is transforming human security to help make a safer, faster, and better experience for the world’s most iconic venues and companies as well as schools, hospitals, and p..."
Booth = "2801"

[["investigation surveillance detection"]]
Exhibitor = "FARO Technologies Inc."
Summary = "FARO® enables public safety, law enforcement and fire professionals to capture, analyze and visualize data to provide unbiased 2D and 3D digital information for investigation and pre-incident planning..."
Booth = "1241"

[["investigation surveillance detection"]]
Exhibitor = "FirstTwo"
Summary = "Founded by experts in the data intelligence space, US based FirstTwo provides location-based visual intelligence to over 2,300 public safety agencies across the United States. Officers can visualize i..."
Booth = "1587"

[["investigation surveillance detection"]]
Exhibitor = "Flock Safety"
Summary = "Flock Safety has built the first public safety operating system that helps neighborhoods, businesses, and law enforcement in 4000+ cities work together to eliminate crime, protect privacy, and mitigat..."
Booth = "1623"
Prefixes = ["B4:1E:52"]

[["investigation surveillance detection"]]
Exhibitor = "Gridless"
Summary = "Gridless is a battery technology company that designs and manufactures products for enterprise and government customers. With a passion for solving challenging power problems, Gridless aims to change ..."
Booth = "411"

[["investigation surveillance detection"]]
Exhibitor = "Insight LPR"
Summary = "Your second line of defense. Insight LPR partners with law enforcement to bring the latest and greatest technology to help solve crimes. We connect you to our commercial partners and provide you ..."
Booth = "4505"

[["investigation surveillance detection"]]
Exhibitor = "JAMAR Technologies, Inc."
Summary = "None"
Booth = "3911"

[["investigation surveillance detection"]]
Exhibitor = "Jenoptik Smart Mobility Solutions"
Summary = "Jenoptik Smart Mobility Solutions provides photonics-based, innovative and sustainable solutions, including technology and services for road safety and security. As an end-to-end solution provider, we..."
Booth = "1093"

[["investigation surveillance detection"]]
Exhibitor = "JSI"
Summary = "None"
Booth = "2294"

[["investigation surveillance detection"]]
Exhibitor = "Kaseware, Inc."
Summary = "Kaseware helps organizations solve complex investigations quickly and efficiently, ensuring the safety of people and the protection of property. Our software allows you to collect, analyze, and connec..."
Booth = "573"

[["investigation surveillance detection"]]
Exhibitor = "Laser Tech"
Summary = "At Laser Tech, we proudly offer an extensive selection of affordable lidar measurement solutions that help you navigate through the ever-changing environment of traffic safety enforcement. From spee..."
Booth = "1078"

[["investigation surveillance detection"]]
Exhibitor = "LeadsOnline"
Summary = "LeadsOnline is an investigative technology company that serves law enforcement agencies in over 80 countries. Our products are used by investigators, crime analysts, forensic examiners, and other prof..."
Booth = "1330"

[["investigation surveillance detection"]]
Exhibitor = "Leonardo/ELSAG"
Summary = "At Leonardo, we are dedicated to providing proprietary advanced ALPR technology to law enforcement agencies, parking authorities, toll operators and access control organizations through our ELSAG ALPR..."
Booth = "1303"

[["investigation surveillance detection"]]
Exhibitor = "LiveView Technologies"
Summary = "Our mission at LiveView Technologies is to make the world safer and more secure through mobile surveillance technology. With a focus on intelligent safety, LVT’s innovative mobile units integrate sola..."
Booth = "511"

[["investigation surveillance detection"]]
Exhibitor = "MaestroVision"
Summary = "Empower Your Investigations with MaestroVision’s Interview Recording System Efficiently obtain the evidence you need with our user-friendly interview recording software and media library."
Booth = "914"

[["investigation surveillance detection"]]
Exhibitor = "MatrixSpace"
Summary = "MatrixSpace is re-imagining radar. We are addressing the next generation of AI-enabled sensing so that objects can be identified, and data collected in real-time - no cloud access required. We’re buil..."
Booth = "2118"

[["investigation surveillance detection"]]
Exhibitor = "METIS Intelligence"
Summary = "None"
Booth = "2291"

[["investigation surveillance detection"]]
Exhibitor = "Metrohm"
Summary = "None"
Booth = "377"

[["investigation surveillance detection"]]
Exhibitor = "Milestone"
Summary = "BriefCam is the industry’s leading provider of VIDEO SYNOPSIS® and Deep Learning solutions for rapid video review and search, face recognition, real-time alerting and quantitative video insights. By t..."
Booth = "3309"

[["investigation surveillance detection"]]
Exhibitor = "Mission Darkness"
Summary = "None"
Booth = "315"

[["investigation surveillance detection"]]
Exhibitor = "MPD, Inc."
Summary = "CMI, Kustom Signals and MPH Industries, having over 150 years of combined experience serving our customers with Breath Alcohol testing, Radar, Lidar, Body Worn Video, In-Car Video, and Speed Awareness..."
Booth = "493"

[["investigation surveillance detection"]]
Exhibitor = "NDI Recognition Systems"
Summary = "None"
Booth = "1041"

[["investigation surveillance detection"]]
Exhibitor = "NightRide Thermal Inc."
Summary = "None"
Booth = "237"

[["investigation surveillance detection"]]
Exhibitor = "Parsons"
Summary = "Parsons (NYSE:PSN) is a leading disruptive technology provider in the national security and global infrastructure markets, with capabilities across cyber and intelligence, space and missile defense, t..."
Booth = "3723"

[["investigation surveillance detection"]]
Exhibitor = "Penlink"
Summary = "For 35 years, PenLink has been the industry-preferred provider for communications, surveillance, and forensics data analysis. Our state-of-the-art solutions help law enforcement collect, normalize, an..."
Booth = "3001"

[["investigation surveillance detection"]]
Exhibitor = "Peregrine"
Summary = "Peregrine is the leading platform for public safety agencies, providing real-time data integration and visualization in one place for better decision-making in the moments that matter most. We hel..."
Booth = "1823"

[["investigation surveillance detection"]]
Exhibitor = "Phaser Services"
Summary = "None"
Booth = "2289"

[["investigation surveillance detection"]]
Exhibitor = "Planar"
Summary = "Planar is a global leader in digital display technology designed for mission-critical 24x7x365 applications, providing premier solutions for the world’s most demanding environments. Planar fine pitch ..."
Booth = "1809"

[["investigation surveillance detection"]]
Exhibitor = "Pro-Vision Video Systems"
Summary = "Founded in 2003, Pro-Vision is a leading video technology solutions provider. Pro-Vision solutions include vehicle video recording systems, body-worn cameras, data management and cloud-based storage s..."
Booth = "357"

[["investigation surveillance detection"]]
Exhibitor = "RAKIA"
Summary = "None"
Booth = "3430"

[["investigation surveillance detection"]]
Exhibitor = "Regional Information Sharing System RISS"
Summary = "RISS is a congressionally funded program that provides information sharing, intelligence and analytical services for law enforcement agencies. The RISS Secure Cloud (RISSNET) connects law enforcement..."
Booth = "1555"

[["investigation surveillance detection"]]
Exhibitor = "Rekor Systems"
Summary = "None"
Booth = "607"

[["investigation surveillance detection"]]
Exhibitor = "Rigaku Analytical Devices"
Summary = "The NEW Rigaku CQL Narc-ID is the latest in handheld technology that provides presumptive ID of unknown substances in seconds. With a standard library that contains narcotics, precursor chemicals, an..."
Booth = "3302"

[["investigation surveillance detection"]]
Exhibitor = "Sensys Gatso USA"
Summary = "None"
Booth = "2327"

[["investigation surveillance detection"]]
Exhibitor = "SoundThinking"
Summary = "SoundThinking is a public safety technology company that combines transformative solutions and strategic advisory services for law enforcement and civic leadership. We are trusted by more than 250 cus..."
Booth = "1929"

[["investigation surveillance detection"]]
Exhibitor = "Stop For Kids, LLC"
Summary = "Stop For Kids is a road safety company focused on protecting children and families by promoting responsible driving near schools and residential areas. With patented AI technology, we offer Automated ..."
Booth = "2808"

[["investigation surveillance detection"]]
Exhibitor = "Techline Technologies, Inc."
Summary = "Manufacturer of Trauma Simulations and Training Manikins; Mobile Training Support for Active Shooter/Multiple Casualty Incident Drills; Distribution of Medical Supplies; and builder of custom Conceal..."
Booth = "2101"

[["investigation surveillance detection"]]
Exhibitor = "Thomson Reuters"
Summary = "Law enforcement agencies are tasked with the immense duty of keeping communities safe. As the type of threats communities face become more complex, law enforcement personnel need solutions that enable..."
Booth = "917"

[["investigation surveillance detection"]]
Exhibitor = "Traffic Logix"
Summary = "None"
Booth = "1511"

[["investigation surveillance detection"]]
Exhibitor = "U.S. Postal Inspection Service"
Summary = "The mission of the U.S. Postal Inspection Service is to support and protect the U.S. Postal Service and its employees, infrastructure, and customers; enforce the laws that defend the nation's mail sys..."
Booth = "855"

[["investigation surveillance detection"]]
Exhibitor = "Ver-Mac, Inc."
Summary = "Ver-Mac is a leading manufacturer of mobile electronic traffic control equipment and lighting/security equipment. With a strong presence in both the Canadian and US markets, Ver-Mac products are distr..."
Booth = "3108"

[["investigation surveillance detection"]]
Exhibitor = "Verkada"
Summary = "Designed with simplicity in mind, Verkada's six product lines — video security cameras, access control, environmental sensors, alarms, workplace, and intercoms — provide unparalleled building security..."
Booth = "1875"

[["investigation surveillance detection"]]
Exhibitor = "Videray Technologies"
Summary = "Videray is a proud American company formed to disrupt the market with its advanced non-intrusive inspection and imaging technologies deployed worldwide. We believe that information and intelligence em..."
Booth = "342"

[["investigation surveillance detection"]]
Exhibitor = "Visionations/CrimePad"
Summary = "Visionations is the maker of CrimePad: complete, easy-to-use, collaborative case and incident management for Officers, CSIs, Detectives, Supervisors and Chiefs. CrimePad allows for central communicati..."
Booth = "1392"

[["investigation surveillance detection"]]
Exhibitor = "VITRONIC Machine Vision"
Summary = "VITRONIC is the world's leading innovation driver for industrial image processing. VITRONIC develops forward-looking solutions of specialized products and software for image-based quality inspection, ..."
Booth = "4017"

[["investigation surveillance detection"]]
Exhibitor = "Whooster, Inc"
Summary = "Whooster provides investigative data solution tools to law enforcement, government agency and business sector clients who need to find out – ‘Who’, ‘What’ and ‘Where’ as well as discovering non-obviou..."
Booth = "1676"

[["investigation surveillance detection"]]
Exhibitor = "Wireless CCTV LLC"
Summary = "WCCTV is the USA’s leading supplier of mobile surveillance cameras for law enforcement applications, with over 150 agencies utilizing our cameras to augment their departments. Our-rapid deployment ..."
Booth = "479"
