[["personal tactical equipment"]]
Exhibitor = "5.11 TACTICAL"
Summary = "5.11 is the pioneer and world-leading maker of purpose-built gear. Grounded in the knowledge, experience, and insights of professionals and elite end users around the world, 5.11 makes technical produ..."
Booth = "617"

[["personal tactical equipment"]]
Exhibitor = "Advanced Manufacturing Group"
Summary = "None"
Booth = "1904"

[["personal tactical equipment"]]
Exhibitor = "Advanced Security Technologies LLC"
Summary = "None"
Booth = "1207"

[["personal tactical equipment"]]
Exhibitor = "Amchar Wholesale, Inc."
Summary = "AmChar Wholesale Inc. is a full-line shooting sports distributor and has been in business for over 50 years! Our philosophy is to provide the best products at a competitive price. We have become one o..."
Booth = "815"

[["personal tactical equipment"]]
Exhibitor = "Amwear USA INC- United Uniform Mfg."
Summary = "None"
Booth = "2110"

[["personal tactical equipment"]]
Exhibitor = "Angel Armor"
Summary = "Angel Armor® exists to protect and preserve the pursuit of life, liberty and happiness for law enforcement and their families by providing advanced ballistic armor solutions. Angel Armor has developed..."
Booth = "1223"

[["personal tactical equipment"]]
Exhibitor = "Armor Express"
Summary = "Armor Express is a leading manufacturer and distributor of high-performance body armor systems and related protective solutions. Founded in 2005, the Company has grown to become one of the largest pro..."
Booth = "2117"

[["personal tactical equipment"]]
Exhibitor = "Armor Research Company"
Summary = "Lightest, Rifle-Rated, compact response shields on the market."
Booth = "1289"

[["personal tactical equipment"]]
Exhibitor = "Ben's Uniforms, Inc"
Summary = "None"
Booth = "207"

[["personal tactical equipment"]]
Exhibitor = "Blade-Tech Holsters"
Summary = "Blade-Tech Holsters' world-class products are the everyday carry gear of choice for many citizens, military and law enforcement users worldwide. For over two decades, Blade-Tech has continued to lead ..."
Booth = "585"

[["personal tactical equipment"]]
Exhibitor = "Blauer Manufacturing Co."
Summary = "Blauer is a leader in developing and manufacturing high-performance, protective uniform apparel for the public safety market. Relentless pursuit of the best technology and constant attention to detail..."
Booth = "2023"

[["personal tactical equipment"]]
Exhibitor = "Blue Force Gear"
Summary = "None"
Booth = "233"

[["personal tactical equipment"]]
Exhibitor = "Boston Leather Inc."
Summary = "None"
Booth = "1684"

[["personal tactical equipment"]]
Exhibitor = "Bounce Imaging"
Summary = "Bounce Imaging makes a suite of tactical, 360-degree camera systems that keep first responders, warfighters, and civilians safer during hostage, high-risk warrant, and active shooter situations, as we..."
Booth = "756"

[["personal tactical equipment"]]
Exhibitor = "Bunker Supply"
Summary = "Bunker Supply is a design-forward US military contractor that develops and manufactures optimized equipment for agents in the field. We are uniquely equipped to support the mission of our Government a..."
Booth = "2274"

[["personal tactical equipment"]]
Exhibitor = "Chinook Medical Gear"
Summary = "Chinook Medical Gear is a certified Veteran Owned and Native American 8(a) Owned Small Business that provides custom medical solutions for the harshest environments. Since 1990, Chinook Medical Gear h..."
Booth = "214"

[["personal tactical equipment"]]
Exhibitor = "Clark Nexsen"
Summary = "For more than 40 years, Clark Nexsen's public safety design experts have served law enforcement agencies and private citizens across the country by designing and renovating public safety training faci..."
Booth = "419"

[["personal tactical equipment"]]
Exhibitor = "Condor Outdoor Products, Inc."
Summary = "Providing tactical gear since 1994. We have a wide range of tactical gear and apparel that includes everything from highly specialized outdoor jackets, to state-of-the-art backpacks, to gear bags,..."
Booth = "740"

[["personal tactical equipment"]]
Exhibitor = "Covert Armor International LLC"
Summary = "Covert Armor International, LLC designs, manufactures and distributes an elite line of ballistic personal protective equipment (PPE) for first responders, military and security personnel who put thems..."
Booth = "2155"

[["personal tactical equipment"]]
Exhibitor = "DragonForce"
Summary = "DragonForce is an industry leading provider of command and control, incident management solutions to the domestic and international public safety community. Its DragonForce team collaboration platform..."
Booth = "1488"

[["personal tactical equipment"]]
Exhibitor = "Eleven 10 LLC"
Summary = "At Eleven 10, we manufacture self-aid and buddy-aid gear that provides instant access to lifesaving equipment, assuring that medical aid can be administered within seconds of an injury. This helps red..."
Booth = "2017"

[["personal tactical equipment"]]
Exhibitor = "Energetic Armament"
Summary = "Energetic Armament engineers high performance firearms silencers for the most demanding Military & Law Enforcement applications. Weapon suppressors provide a critical safety function protecting office..."
Booth = "1388"

[["personal tactical equipment"]]
Exhibitor = "ExecDefense USA"
Summary = "RIOT GEAR LEADERS! CHECK OUT OUR RIOT HELMETS, RIOT SUITS, RIOT SHIELDS AND BALLISTIC HELMETS!"
Booth = "3529"

[["personal tactical equipment"]]
Exhibitor = "First Line Technology"
Summary = "None"
Booth = "2324"

[["personal tactical equipment"]]
Exhibitor = "Flying Cross"
Summary = "Flying Cross is a world leader in the design and manufacture of high-quality, precision-crafted uniform apparel for the U.S. military, public safety, fire, and postal service markets. Since 1842, Flyi..."
Booth = "1447"

[["personal tactical equipment"]]
Exhibitor = "Galvion"
Summary = "At Galvion, we design, develop and deliver best-in-class head systems, as well as innovative power and data management solutions for military and tactical operators worldwide. We engineer advanced con..."
Booth = "4315"

[["personal tactical equipment"]]
Exhibitor = "GC Shields"
Summary = "GC is a world leader in advanced materials research, development and design. We have created our patented GC Shield technology to create the strongest, lightest and most resilient ballistic shields av..."
Booth = "1856"

[["personal tactical equipment"]]
Exhibitor = "Guardian Angel Devices"
Summary = "Guardian Angel™ wearable safety lights are designed with a core belief that personal lighting technology will make the world a safer place. Our mission is, and always will be, to save lives by develop..."
Booth = "304"

[["personal tactical equipment"]]
Exhibitor = "H7 America Inc."
Summary = "None"
Booth = "337"

[["personal tactical equipment"]]
Exhibitor = "HERO'S PRIDE"
Summary = "Hero’s Pride™ is a duty gear and uniform accessories company manufacturing high quality products for law enforcement and military agencies. Family owned and operated, we’re dedicated to supporting the..."
Booth = "1227"

[["personal tactical equipment"]]
Exhibitor = "High Speed Gear, Inc"
Summary = "None"
Booth = "413"

[["personal tactical equipment"]]
Exhibitor = "Holmatro Inc"
Summary = "None"
Booth = "4201"

[["personal tactical equipment"]]
Exhibitor = "Kore Essentials Inc."
Summary = "We design and manufacture innovative gun belts, tactical belts and duty belts for gun owners, security professionals, law enforcement and military personnel Worldwide. Our belts use a unique track sys..."
Booth = "4313"

[["personal tactical equipment"]]
Exhibitor = "Marrero Armor, LLC"
Summary = "Lightweight. Reliable. Tactical. Affordable. Marrero Armor designs and manufactures ballistic products to provide front-line defenders with best-in-class life saving products. Established in 20..."
Booth = "414"

[["personal tactical equipment"]]
Exhibitor = "Merrell Tactical"
Summary = "None"
Booth = "1290"

[["personal tactical equipment"]]
Exhibitor = "Michael Lupton Associates"
Summary = "None"
Booth = "2195"

[["personal tactical equipment"]]
Exhibitor = "Mistral Inc."
Summary = "None"
Booth = "3011"

[["personal tactical equipment"]]
Exhibitor = "Nightstick"
Summary = "NIGHTSTICK® – Performance, Quality and Value Nightstick, designed and manufactured by Bayco Products, Inc., is a global brand of professional lighting products including flashlights, headlamps and ..."
Booth = "330"

[["personal tactical equipment"]]
Exhibitor = "North American Rescue, LLC"
Summary = "None"
Booth = "814"

[["personal tactical equipment"]]
Exhibitor = "OD Kit LLC / ODkit.com"
Summary = "Manufacturer and distributor of the original, most trusted Narcan carry device / holster."
Booth = "3623"

[["personal tactical equipment"]]
Exhibitor = "Office Furniture EZ, LLC"
Summary = "OFFICE FURNITURE EZ is a New/used Office Furniture, Cubicle and Seating product seller/provider. We perform FREE Site surveys, Space planning, CAD layout and design services. We also offer complete f..."
Booth = "2292"

[["personal tactical equipment"]]
Exhibitor = "Otis Technology"
Summary = "Otis Technology is known for manufacturing the most advanced gun cleaning systems and accessories available. The superior Breech-to-Muzzle® design combined with unmatched quality has positioned Otis ..."
Booth = "622"

[["personal tactical equipment"]]
Exhibitor = "OTTO Engineering"
Summary = "OTTO Engineering designs and manufactures innovative two-way radio accessories, hearing protection and location tracking equipment developed for high-precision applications in mission critical environ..."
Booth = "2610"

[["personal tactical equipment"]]
Exhibitor = "Patriot3"
Summary = "Patriot3 is a premier provider and authority in Elevated Tactical Systems, Ballistic Operations and Specialty Maritime Products. Patriot3 has products in operation throughout the world and has export..."
Booth = "811"

[["personal tactical equipment"]]
Exhibitor = "Peerless Handcuff Company"
Summary = "Setting the standard since 1914, Peerless offers a full line of metallic restraining devices and accessories. Products include chain link, hinged and oversize handcuffs, leg irons, waist chains, keys ..."
Booth = "1287"

[["personal tactical equipment"]]
Exhibitor = "Penn Emblem Company"
Summary = "None"
Booth = "392"

[["personal tactical equipment"]]
Exhibitor = "PH&S Products LLC"
Summary = "PH&S Products, LLC is a leading supplier of high quality gloves for the First Responders, EMS, Law Enforcement and the Public Health & Safety Community. We manufacture gloves for the safety and person..."
Booth = "3928"

[["personal tactical equipment"]]
Exhibitor = "Point Blank Enterprises, Inc."
Summary = "Point Blank Enterprises, Inc. is the worldwide leader in the development, manufacturing and distribution of protective solutions for the U.S. Military and Department of Defense, Federal Agencies and d..."
Booth = "931"

[["personal tactical equipment"]]
Exhibitor = "Project 7 / Aardvark"
Summary = "TACTICAL ARMOR REIMAGINED FOR TACTICAL OPERATORS PROJECT7 is the culmination of years of research and development geared toward producing the ultimate integrated tactical armor systems."
Booth = "496"

[["personal tactical equipment"]]
Exhibitor = "Rocky Brands Inc."
Summary = "Rocky is a hard-working company that builds rugged, reliable, innovative boots for the hard-working men and women who depend on us. We serve those protecting our communities and serving our country."
Booth = "1686"

[["personal tactical equipment"]]
Exhibitor = "Safeguard Medical"
Summary = "None"
Booth = "3408"

[["personal tactical equipment"]]
Exhibitor = "Safeware Inc."
Summary = "Safeware has helped public procurement and first responders prepare their teams with the products and solutions they need when they need it since 1979. Just like you, our company is full of people wh..."
Booth = "1917"

[["personal tactical equipment"]]
Exhibitor = "Sarkar Tactical Inc"
Summary = "None"
Booth = "2295"

[["personal tactical equipment"]]
Exhibitor = "SILYNX Communications, Inc"
Summary = "None"
Booth = "241"

[["personal tactical equipment"]]
Exhibitor = "Slate Solutions"
Summary = "Slate Solutions is dedicated to providing high-quality, high-performing armor solutions with over 30 years of experience. We not only meet the required performance standards but go beyond to protect a..."
Booth = "317"

[["personal tactical equipment"]]
Exhibitor = "Sparta 2002 Designs and Promotions Inc"
Summary = "Sparta has been creating all types of custom merchandise for law enforcement, for over 30 years!!!! Manufacturing unique pewter merchandise like key chains, ornaments, mug crests, coasters, lapel pin..."
Booth = "1784"

[["personal tactical equipment"]]
Exhibitor = "Spartan Armor Systems"
Summary = "None"
Booth = "3112"

[["personal tactical equipment"]]
Exhibitor = "Spire Ranges"
Summary = "None"
Booth = "478"

[["personal tactical equipment"]]
Exhibitor = "Streamlight, Inc."
Summary = "Streamlight Inc. manufactures a variety of portable lighting products including rechargeable and standard battery, precision-engineered flashlights, tactical lights, lanterns and accessories for use i..."
Booth = "1788"

[["personal tactical equipment"]]
Exhibitor = "Strong Leather Co."
Summary = "Leading manufacturer of leather badge cases and holders, gear bags, holster and duty accessories."
Booth = "1285"

[["personal tactical equipment"]]
Exhibitor = "Super Seer Corporation"
Summary = "Seer helmets are made in USA for law enforcement for 55 years. Products include motorcycle, mounted, riot, corrections, general duty and ballistic helmets. Specialty products include emergency helmet ..."
Booth = "1579"

[["personal tactical equipment"]]
Exhibitor = "TacMed Solutions"
Summary = "None"
Booth = "1891"

[["personal tactical equipment"]]
Exhibitor = "Technics&Production BV"
Summary = "None"
Booth = "3327"

[["personal tactical equipment"]]
Exhibitor = "Thermo Fisher Scientific"
Summary = "Thermo Fisher Scientific supplies innovative solutions for the world’s law enforcement agencies. The Thermo Scientific™ TruNarc™ and 1064Defender™ narcotics analyzers can identify hundreds of narcotic..."
Booth = "901"

[["personal tactical equipment"]]
Exhibitor = "TrafFix Devices - Block Axess"
Summary = "TrafFix Devices, Inc. is a manufacturer and global distributor of barriers, crowd control, traffic security, highway barricades, crash attenuators, signage and delineation products. Providing a full l..."
Booth = "3429"

[["personal tactical equipment"]]
Exhibitor = "TRAUMAGEL"
Summary = "TRAUMAGEL® is an FDA approved hemostatic gel designed to control moderate to severe bleeding from external traumatic injuries. TRAUMAGEL deploys and controls bleeding in seconds, minimizing blood loss..."
Booth = "2296"

[["personal tactical equipment"]]
Exhibitor = "Trikke Professional Mobility"
Summary = "Trikke Professional Mobility is a US-based manufacturer and sole distributor of rugged professional-grade personal electric patrol vehicles with a proprietary 3-wheel cambering design for efficientl..."
Booth = "2185"

[["personal tactical equipment"]]
Exhibitor = "TYR Tactical"
Summary = "Established in 2010, TYR Tactical® is a leading global manufacturer of tactical gear offering a wide range of products designed to meet the needs of tactical operators, including plate carriers and ve..."
Booth = "4417"

[["personal tactical equipment"]]
Exhibitor = "U.S. Armor Corp."
Summary = "Body Armor - Tailor-Made - Custom fit - Made in USA - NIJ 0101.06 Certified - Over 38 years in business manufacturing concealable armor, tactical armor, international armor products, breacher and bo..."
Booth = "711"

[["personal tactical equipment"]]
Exhibitor = "UNI&FORMA d.o.o."
Summary = "None"
Booth = "243"

[["personal tactical equipment"]]
Exhibitor = "Unity Tactical"
Summary = "None"
Booth = "340"

[["personal tactical equipment"]]
Exhibitor = "Velocity Systems"
Summary = "None"
Booth = "684"

[["personal tactical equipment"]]
Exhibitor = "Verco Materials"
Summary = "Verco Materials originated as a spin-off of high-performance boron carbide technology developed at the Georgia Institute of Technology. After a number of years of DOD-supported research with the Army ..."
Booth = "3304"

[["personal tactical equipment"]]
Exhibitor = "Zero9 Solutions"
Summary = "Zero9 Holsters is a Cleveland, Ohio based duty gear manufacturer providing solutions for the public safety industry. Law Enforcement owned and operated - small business. Zero9 Holsters creates gear ..."
Booth = "525"
