[[restraints]]
Exhibitor = "Peerless Handcuff Company"
Summary = "Setting the standard since 1914, Peerless offers a full line of metallic restraining devices and accessories. Products include chain link, hinged and oversize handcuffs, leg irons, waist chains, keys ..."
Booth = "1287"

[[restraints]]
Exhibitor = "Rampart USA Corporation"
Summary = "None"
Booth = "244"

[[restraints]]
Exhibitor = "Safe Restraints, Inc"
Summary = "None"
Booth = "3729"
