[["weapon firearms"]]
Exhibitor = "Aero Precision/Aero Defense"
Summary = "Aero Precision manufactures a full line of mission driven products for our Law Enforcement and Military customers at our world class manufacturing facility in Tacoma, Washington. Our goal is to ensur..."
Booth = "334"

[["weapon firearms"]]
Exhibitor = "Alien Gear Holsters"
Summary = "None"
Booth = "3923"

[["weapon firearms"]]
Exhibitor = "Amchar Wholesale, Inc."
Summary = "AmChar Wholesale Inc. is a full-line shooting sports distributor and has been in business for over 50 years! Our philosophy is to provide the best products at a competitive price. We have become one o..."
Booth = "815"

[["weapon firearms"]]
Exhibitor = "AUFIRE"
Summary = "None"
Booth = "3925"

[["weapon firearms"]]
Exhibitor = "B&T USA"
Summary = "None"
Booth = "300"

[["weapon firearms"]]
Exhibitor = "Beretta USA Corp."
Summary = "Beretta, established in 1526, is the oldest industrial dynasty in the world tracing its roots through 16 generations of continuous family ownership. Beretta USA Corp. was founded in 1977 and supplies ..."
Booth = "432"

[["weapon firearms"]]
Exhibitor = "Century Arms"
Summary = "Born over 60 years ago with its roots in the surplus business, Century Arms has an extensive history of purchasing from Law Enforcement and Government Agencies, both domestic and abroad. Century Arms ..."
Booth = "4010"

[["weapon firearms"]]
Exhibitor = "Colt Manufacturing LLC"
Summary = "None"
Booth = "2335"

[["weapon firearms"]]
Exhibitor = "D & R Electronics"
Summary = "D & R is a leading Manufacturer and supplier of equipment for emergency services vehicles. D & R manufactures emergency vehicle lighting, cabinets, storage solutions, power distribution systems, LED c..."
Booth = "1801"

[["weapon firearms"]]
Exhibitor = "Daniel Defense"
Summary = "Daniel Defense is a family owned and privately held firearms manufacturer located in Black Creek, Georgia. Founded in 2000 by Founder/Executive Chairman Marty Daniel, the company was born from Marty’s..."
Booth = "4317"

[["weapon firearms"]]
Exhibitor = "DART Range"
Summary = "Digimation is a leading provider of virtual small arms training systems for defense and police forces. The DART™ simulator has set new standards for portability and affordability and is currently in u..."
Booth = "3519"

[["weapon firearms"]]
Exhibitor = "Dead Air Silencers"
Summary = "None"
Booth = "3822"

[["weapon firearms"]]
Exhibitor = "En.Range, Inc."
Summary = "None"
Booth = "1059"

[["weapon firearms"]]
Exhibitor = "Evolve Range Solutions"
Summary = "None"
Booth = "1687"

[["weapon firearms"]]
Exhibitor = "FN America"
Summary = "None"
Booth = "2248"

[["weapon firearms"]]
Exhibitor = "Glock, Inc."
Summary = "GLOCK is a leading global manufacturer of pistols and accessories. GLOCK's superior engineering has produced a pistol with a rugged polymer frame, providing industry-leading reliability shot after sho..."
Booth = "623"

[["weapon firearms"]]
Exhibitor = "GUNBUSTERS"
Summary = "GunBusters provides our SAFE, SIMPLE and SECURE firearms destruction program FREE OF CHARGE to law enforcement agencies across the nation. This pulverization process destroys firearms in a manner tha..."
Booth = "710"

[["weapon firearms"]]
Exhibitor = "Heckler & Koch"
Summary = "Heckler & Koch is the world’s premier small arms systems company and a major supplier to the commercial market, global military, and federal law enforcement agencies. An innovative leader in design an..."
Booth = "1851"

[["weapon firearms"]]
Exhibitor = "Henry Repeating Arms"
Summary = "Henry Repeating Arms is the leading lever action manufacturer and one of the top-five long gun manufacturers in the USA. Our goal is to manufacture a line of classic, well-crafted firearms that every ..."
Booth = "2097"

[["weapon firearms"]]
Exhibitor = "Holosun Technologies"
Summary = "Since 2013, Holosun has been committed to creating innovative optic and laser/IR technologies for a broad range of shooting, hunting, law enforcement and military needs. Today, Holosun is at the foref..."
Booth = "529"

[["weapon firearms"]]
Exhibitor = "HUXWRX Safety Co."
Summary = "IN 2009, OSS INTRODUCED THE FIRST FLOW-THROUGH® SUPPRESSOR. ENGINEERED TO DELIVER SUPERIOR SOUND SUPPRESSION WITHOUT ADVERSELY AFFECTING THE WEAPON SYSTEM, FLOW-THROUGH® TECHNOLOGY WOULD GO ON TO COMP..."
Booth = "333"

[["weapon firearms"]]
Exhibitor = "Laser Ammo USA Inc"
Summary = "Laser Ammo is the worldwide leading provider of superior laser base firearms training solutions for Federal, Law Enforcement Agencies, & Military Markets. We offer portable, realistic and simple to ..."
Booth = "1056"

[["weapon firearms"]]
Exhibitor = "LSC Destruction"
Summary = "LSC has been in business since 2009 we have helped agencies all over the country destroy and dispose of contraband from evidence rooms. As we have continued to evolve as a business we work to expand o..."
Booth = "1205"

[["weapon firearms"]]
Exhibitor = "Military and Police Targets inc."
Summary = "None"
Booth = "2240"

[["weapon firearms"]]
Exhibitor = "MILO"
Summary = "MILO is a world-leading provider of interactive simulation training, curriculum, range design, and equipment. We are widely regarded as the nation’s fastest-growing manufacturer of best-in-class firea..."
Booth = "533, 624"

[["weapon firearms"]]
Exhibitor = "Mitchell Defense"
Summary = "None"
Booth = "4318"

[["weapon firearms"]]
Exhibitor = "Mossberg"
Summary = "Founded in 1919, O.F. Mossberg & Sons, Inc., is the oldest family-owned firearms manufacturer in America, and is the largest pump-action shotgun manufacturer in the world. Celebrating over 100 years o..."
Booth = "686"

[["weapon firearms"]]
Exhibitor = "NSSF"
Summary = "NSSF is the trade association of the firearms industry. NSSF leads the way in advocating for the industry and its business and jobs, keeping guns out of the wrong hands, encouraging enjoyment of recr..."
Booth = "613"

[["weapon firearms"]]
Exhibitor = "PepperBall"
Summary = "PepperBall is the leading provider of non-lethal solutions. Their products, which include pneumatic air launchers and PepperBall projectiles, offer law enforcement a versatile and effective tool for m..."
Booth = "1324"

[["weapon firearms"]]
Exhibitor = "Range Systems"
Summary = "None"
Booth = "4016"

[["weapon firearms"]]
Exhibitor = "ROCK RIVER ARMS INC"
Summary = "None"
Booth = "1154"

[["weapon firearms"]]
Exhibitor = "Rugged Suppressors"
Summary = "None"
Booth = "3722"

[["weapon firearms"]]
Exhibitor = "Setina Manufacturing Company, Inc."
Summary = "Setina Manufacturing Company is a leading producer of Law Enforcement Vehicle Equipment for agencies worldwide. Specializing in Prisoner Transport Partitions and Prisoner Transport Seating, Push Bump..."
Booth = "963"

[["weapon firearms"]]
Exhibitor = "SIG SAUER"
Summary = "SIG SAUER, Inc. is a leading provider and manufacturer of firearms, electro-optics, ammunition, airguns, suppressors, and training. For over 250 years SIG SAUER, Inc. has evolved, and thrived, by ble..."
Booth = "1695"

[["weapon firearms"]]
Exhibitor = "Smart Firearms Training Devices"
Summary = "We offer the most advanced training gun featuring our patented Unintentional Discharge Zone Sensor which alerts the student and instructor to intrusions in the trigger guard when no shots are being fi..."
Booth = "2179"

[["weapon firearms"]]
Exhibitor = "Smith & Wesson Inc."
Summary = "Smith & Wesson is a U.S. - based leader in firearm manufacturing and design, delivering a broad portfolio of quality firearms, related products, and training to the U.S. consumer and law enforcement m..."
Booth = "1000"

[["weapon firearms"]]
Exhibitor = "Springfield Armory"
Summary = "About Springfield Armory® In 1794, the original Springfield Armory began manufacturing muskets for the defense of our young, free Republic. The Armory functioned as a firearms supplier for every majo..."
Booth = "4215"

[["weapon firearms"]]
Exhibitor = "Staccato 2011"
Summary = "None"
Booth = "2914"

[["weapon firearms"]]
Exhibitor = "Ti Training Corp"
Summary = "Home of The RECON Simulation Training System. The only upgradeable simulation system in the industry. Recon Core, 180, 300, and Sim-House. Thousands of scenarios and skill builders, video gaming ..."
Booth = "1641"

[["weapon firearms"]]
Exhibitor = "Troy Industries"
Summary = "Established in 2003 and based in Clarksville, Tennessee, TROY® Industries designs, manufactures and markets innovative, advanced small arms components, accessories, and weapons for professional, duty ..."
Booth = "1980"

[["weapon firearms"]]
Exhibitor = "TSN US LLC"
Summary = "None"
Booth = "2278"

[["weapon firearms"]]
Exhibitor = "VirTra"
Summary = "VirTra provides law enforcement agencies with immersive training solutions to deliver a lifelike experience that is transferrable to the field. Each simulated scenario covers vital topics such as acti..."
Booth = "2033"

[["weapon firearms"]]
Exhibitor = "ZeroEyes"
Summary = "Founded by Navy SEALs, ZeroEyes™ delivers proactive solutions to help combat mass shootings and gun-related violence and provide intel for situational awareness, reducing response times, to save lives..."
Booth = "492"
